name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S . -B build -A win32

      - name: Build
        run: cmake --build build --config MinSizeRel -- /p:Configuration=MinSizeRel

      - name: Create Release
        id: create_release
        shell: pwsh
        run: |
          $headers = @{
            Authorization = "token ${{ secrets.GITHUB_TOKEN }}"
            Accept = "application/vnd.github.v3+json"
          }
          $body = @{
            tag_name = "${{ github.ref_name }}"
            target_commitish = "main"
            name = "Release ${{ github.ref_name }}"
            body = "Release notes"
            draft = $false
            prerelease = $false
          } | ConvertTo-Json
          Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/releases" -Method Post -Headers $headers -Body $body

      - name: Upload Release Asset
        shell: pwsh
        run: |
          $headers = @{
            Authorization = "token ${{ secrets.GITHUB_TOKEN }}"
            Accept = "application/vnd.github.v3+json"
          }
          $release = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}" -Method Get -Headers $headers
          $release_id = $release.id
          $asset_headers = @{
            Authorization = "token ${{ secrets.GITHUB_TOKEN }}"
            "Content-Type" = "application/octet-stream"
          }
          Invoke-RestMethod -Uri "https://uploads.github.com/repos/${{ github.repository }}/releases/$release_id/assets?name=abracadabra.exe" -Method Post -Headers $asset_headers -InFile "./build/MinSizeRel/abracadabra.exe"

